#!/usr/bin/env python3
"""mkstr.py — turn userland source files into C string literals for the kernel.

The kernel publishes a small SDK into the VFS at boot: headers, the occ runtime,
and (from v0.58) the source of the two native tools. Those tools are REAL
PROGRAMS, several hundred lines each, and keeping them as escaped string
literals inside kernel64.c would make them unreadable and uneditable — you
cannot compile-test, diff or review a program that only exists as \\n-spliced
quotes.

So they live as ordinary files under user/, and this script converts them at
build time. The generated header is a build artefact; user/*.oc is the source.

    mkstr.py <out.h> NAME=path [NAME=path ...]
"""
import sys


def emit(name, path):
    with open(path, "r", encoding="utf-8") as f:
        text = f.read()
    out = ["static const char %s[] =" % name]
    for line in text.split("\n")[:-1] if text.endswith("\n") else text.split("\n"):
        esc = line.replace("\\", "\\\\").replace('"', '\\"')
        # A literal "??" can start a trigraph in some dialects; split it so the
        # generated header means exactly what the source said.
        esc = esc.replace("??", '?" "?')
        out.append('    "%s\\n"' % esc)
    if len(out) == 1:
        out.append('    ""')
    out.append("    ;")
    return "\n".join(out)


def main(argv):
    if len(argv) < 3:
        sys.stderr.write(__doc__)
        return 2
    dst = argv[1]
    chunks = [
        # The banner must not contain the sequence slash-star: it lands inside a
        # /* */ comment in the generated header and gcc reads it as a nested
        # comment opener (-Wcomment). Naming the glob before the directory keeps
        # the sentence and drops the digraph.
        "/* GENERATED by tools/mkstr.py from the *.oc files under user/ — DO NOT EDIT.",
        " * Edit the real source files under user/ and rebuild. */",
        "",
    ]
    for spec in argv[2:]:
        name, _, path = spec.partition("=")
        chunks.append("/* ---- %s (from %s) ---- */" % (name, path))
        chunks.append(emit(name, path))
        chunks.append("")
    with open(dst, "w", encoding="utf-8") as f:
        f.write("\n".join(chunks))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
